/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as StudioAdIdRouteImport } from './routes/studio.$adId'
import { Route as StudioAdIdIndexRouteImport } from './routes/studio.$adId.index'
import { Route as StudioAdIdIdeasRouteImport } from './routes/studio.$adId.ideas'
import { Route as StudioAdIdImagesRouteImport } from './routes/studio.$adId.images'
import { Route as StudioAdIdStoryboardRouteImport } from './routes/studio.$adId.storyboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioAdIdRoute = StudioAdIdRouteImport.update({
  id: '/$adId',
  path: '/$adId',
  getParentRoute: () => StudioRoute,
} as any)
const StudioAdIdIndexRoute = StudioAdIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioAdIdRoute,
} as any)
const StudioAdIdIdeasRoute = StudioAdIdIdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => StudioAdIdRoute,
} as any)
const StudioAdIdImagesRoute = StudioAdIdImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => StudioAdIdRoute,
} as any)
const StudioAdIdStoryboardRoute = StudioAdIdStoryboardRouteImport.update({
  id: '/storyboard',
  path: '/storyboard',
  getParentRoute: () => StudioAdIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/studio': typeof StudioRouteWithChildren
  '/studio/$adId': typeof StudioAdIdRouteWithChildren
  '/studio/': typeof StudioIndexRoute
  '/studio/$adId/ideas': typeof StudioAdIdIdeasRoute
  '/studio/$adId/images': typeof StudioAdIdImagesRoute
  '/studio/$adId/storyboard': typeof StudioAdIdStoryboardRoute
  '/studio/$adId/': typeof StudioAdIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/studio': typeof StudioIndexRoute
  '/studio/$adId/ideas': typeof StudioAdIdIdeasRoute
  '/studio/$adId/images': typeof StudioAdIdImagesRoute
  '/studio/$adId/storyboard': typeof StudioAdIdStoryboardRoute
  '/studio/$adId': typeof StudioAdIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/studio': typeof StudioRouteWithChildren
  '/studio/$adId': typeof StudioAdIdRouteWithChildren
  '/studio/': typeof StudioIndexRoute
  '/studio/$adId/ideas': typeof StudioAdIdIdeasRoute
  '/studio/$adId/images': typeof StudioAdIdImagesRoute
  '/studio/$adId/storyboard': typeof StudioAdIdStoryboardRoute
  '/studio/$adId/': typeof StudioAdIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/how-it-works'
    | '/pricing'
    | '/studio'
    | '/studio/$adId'
    | '/studio/'
    | '/studio/$adId/ideas'
    | '/studio/$adId/images'
    | '/studio/$adId/storyboard'
    | '/studio/$adId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/how-it-works'
    | '/pricing'
    | '/studio'
    | '/studio/$adId/ideas'
    | '/studio/$adId/images'
    | '/studio/$adId/storyboard'
    | '/studio/$adId'
  id:
    | '__root__'
    | '/'
    | '/how-it-works'
    | '/pricing'
    | '/studio'
    | '/studio/$adId'
    | '/studio/'
    | '/studio/$adId/ideas'
    | '/studio/$adId/images'
    | '/studio/$adId/storyboard'
    | '/studio/$adId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PricingRoute: typeof PricingRoute
  StudioRoute: typeof StudioRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/$adId': {
      id: '/studio/$adId'
      path: '/$adId'
      fullPath: '/studio/$adId'
      preLoaderRoute: typeof StudioAdIdRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/$adId/': {
      id: '/studio/$adId/'
      path: '/'
      fullPath: '/studio/$adId/'
      preLoaderRoute: typeof StudioAdIdIndexRouteImport
      parentRoute: typeof StudioAdIdRoute
    }
    '/studio/$adId/ideas': {
      id: '/studio/$adId/ideas'
      path: '/ideas'
      fullPath: '/studio/$adId/ideas'
      preLoaderRoute: typeof StudioAdIdIdeasRouteImport
      parentRoute: typeof StudioAdIdRoute
    }
    '/studio/$adId/images': {
      id: '/studio/$adId/images'
      path: '/images'
      fullPath: '/studio/$adId/images'
      preLoaderRoute: typeof StudioAdIdImagesRouteImport
      parentRoute: typeof StudioAdIdRoute
    }
    '/studio/$adId/storyboard': {
      id: '/studio/$adId/storyboard'
      path: '/storyboard'
      fullPath: '/studio/$adId/storyboard'
      preLoaderRoute: typeof StudioAdIdStoryboardRouteImport
      parentRoute: typeof StudioAdIdRoute
    }
  }
}

interface StudioAdIdRouteChildren {
  StudioAdIdIdeasRoute: typeof StudioAdIdIdeasRoute
  StudioAdIdImagesRoute: typeof StudioAdIdImagesRoute
  StudioAdIdStoryboardRoute: typeof StudioAdIdStoryboardRoute
  StudioAdIdIndexRoute: typeof StudioAdIdIndexRoute
}

const StudioAdIdRouteChildren: StudioAdIdRouteChildren = {
  StudioAdIdIdeasRoute: StudioAdIdIdeasRoute,
  StudioAdIdImagesRoute: StudioAdIdImagesRoute,
  StudioAdIdStoryboardRoute: StudioAdIdStoryboardRoute,
  StudioAdIdIndexRoute: StudioAdIdIndexRoute,
}

const StudioAdIdRouteWithChildren = StudioAdIdRoute._addFileChildren(
  StudioAdIdRouteChildren,
)

interface StudioRouteChildren {
  StudioAdIdRoute: typeof StudioAdIdRouteWithChildren
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioAdIdRoute: StudioAdIdRouteWithChildren,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HowItWorksRoute: HowItWorksRoute,
  PricingRoute: PricingRoute,
  StudioRoute: StudioRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
